template: external-bridged-provider
provider: phase
organization: jgautheron
major-version: 0
providerDefaultBranch: main
upstreamProviderOrg: phasehq
publishRegistry: false
languages:
    - go
    - nodejs
    - python
publish:
    sdk: "all,!dotnet,!java"
    cdn: false
license:
    ignore:
        - github.com/phasehq/terraform-provider/shim
pulumiConvert: 1
github-app:
    enabled: false
