// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package phase

import (
	"context"
	"reflect"

	"github.com/jgautheron/pulumi-phase/sdk/go/phase/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func GetSecrets(ctx *pulumi.Context, args *GetSecretsArgs, opts ...pulumi.InvokeOption) (*GetSecretsResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv GetSecretsResult
	err := ctx.Invoke("phase:index/getSecrets:getSecrets", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getSecrets.
type GetSecretsArgs struct {
	AppId string   `pulumi:"appId"`
	Env   string   `pulumi:"env"`
	Key   *string  `pulumi:"key"`
	Path  *string  `pulumi:"path"`
	Tags  []string `pulumi:"tags"`
}

// A collection of values returned by getSecrets.
type GetSecretsResult struct {
	AppId string `pulumi:"appId"`
	Env   string `pulumi:"env"`
	// The provider-assigned unique ID for this managed resource.
	Id      string            `pulumi:"id"`
	Key     *string           `pulumi:"key"`
	Path    *string           `pulumi:"path"`
	Secrets map[string]string `pulumi:"secrets"`
	Tags    []string          `pulumi:"tags"`
}

func GetSecretsOutput(ctx *pulumi.Context, args GetSecretsOutputArgs, opts ...pulumi.InvokeOption) GetSecretsResultOutput {
	return pulumi.ToOutputWithContext(ctx.Context(), args).
		ApplyT(func(v interface{}) (GetSecretsResultOutput, error) {
			args := v.(GetSecretsArgs)
			options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
			return ctx.InvokeOutput("phase:index/getSecrets:getSecrets", args, GetSecretsResultOutput{}, options).(GetSecretsResultOutput), nil
		}).(GetSecretsResultOutput)
}

// A collection of arguments for invoking getSecrets.
type GetSecretsOutputArgs struct {
	AppId pulumi.StringInput      `pulumi:"appId"`
	Env   pulumi.StringInput      `pulumi:"env"`
	Key   pulumi.StringPtrInput   `pulumi:"key"`
	Path  pulumi.StringPtrInput   `pulumi:"path"`
	Tags  pulumi.StringArrayInput `pulumi:"tags"`
}

func (GetSecretsOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetSecretsArgs)(nil)).Elem()
}

// A collection of values returned by getSecrets.
type GetSecretsResultOutput struct{ *pulumi.OutputState }

func (GetSecretsResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetSecretsResult)(nil)).Elem()
}

func (o GetSecretsResultOutput) ToGetSecretsResultOutput() GetSecretsResultOutput {
	return o
}

func (o GetSecretsResultOutput) ToGetSecretsResultOutputWithContext(ctx context.Context) GetSecretsResultOutput {
	return o
}

func (o GetSecretsResultOutput) AppId() pulumi.StringOutput {
	return o.ApplyT(func(v GetSecretsResult) string { return v.AppId }).(pulumi.StringOutput)
}

func (o GetSecretsResultOutput) Env() pulumi.StringOutput {
	return o.ApplyT(func(v GetSecretsResult) string { return v.Env }).(pulumi.StringOutput)
}

// The provider-assigned unique ID for this managed resource.
func (o GetSecretsResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v GetSecretsResult) string { return v.Id }).(pulumi.StringOutput)
}

func (o GetSecretsResultOutput) Key() pulumi.StringPtrOutput {
	return o.ApplyT(func(v GetSecretsResult) *string { return v.Key }).(pulumi.StringPtrOutput)
}

func (o GetSecretsResultOutput) Path() pulumi.StringPtrOutput {
	return o.ApplyT(func(v GetSecretsResult) *string { return v.Path }).(pulumi.StringPtrOutput)
}

func (o GetSecretsResultOutput) Secrets() pulumi.StringMapOutput {
	return o.ApplyT(func(v GetSecretsResult) map[string]string { return v.Secrets }).(pulumi.StringMapOutput)
}

func (o GetSecretsResultOutput) Tags() pulumi.StringArrayOutput {
	return o.ApplyT(func(v GetSecretsResult) []string { return v.Tags }).(pulumi.StringArrayOutput)
}

func init() {
	pulumi.RegisterOutputType(GetSecretsResultOutput{})
}
