// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package phase

import (
	"context"
	"reflect"

	"github.com/jgautheron/pulumi-phase/sdk/go/phase/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

var _ = internal.GetEnvOrDefault

type SecretOverride struct {
	IsActive bool   `pulumi:"isActive"`
	Value    string `pulumi:"value"`
}

// SecretOverrideInput is an input type that accepts SecretOverrideArgs and SecretOverrideOutput values.
// You can construct a concrete instance of `SecretOverrideInput` via:
//
//	SecretOverrideArgs{...}
type SecretOverrideInput interface {
	pulumi.Input

	ToSecretOverrideOutput() SecretOverrideOutput
	ToSecretOverrideOutputWithContext(context.Context) SecretOverrideOutput
}

type SecretOverrideArgs struct {
	IsActive pulumi.BoolInput   `pulumi:"isActive"`
	Value    pulumi.StringInput `pulumi:"value"`
}

func (SecretOverrideArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*SecretOverride)(nil)).Elem()
}

func (i SecretOverrideArgs) ToSecretOverrideOutput() SecretOverrideOutput {
	return i.ToSecretOverrideOutputWithContext(context.Background())
}

func (i SecretOverrideArgs) ToSecretOverrideOutputWithContext(ctx context.Context) SecretOverrideOutput {
	return pulumi.ToOutputWithContext(ctx, i).(SecretOverrideOutput)
}

func (i SecretOverrideArgs) ToSecretOverridePtrOutput() SecretOverridePtrOutput {
	return i.ToSecretOverridePtrOutputWithContext(context.Background())
}

func (i SecretOverrideArgs) ToSecretOverridePtrOutputWithContext(ctx context.Context) SecretOverridePtrOutput {
	return pulumi.ToOutputWithContext(ctx, i).(SecretOverrideOutput).ToSecretOverridePtrOutputWithContext(ctx)
}

// SecretOverridePtrInput is an input type that accepts SecretOverrideArgs, SecretOverridePtr and SecretOverridePtrOutput values.
// You can construct a concrete instance of `SecretOverridePtrInput` via:
//
//	        SecretOverrideArgs{...}
//
//	or:
//
//	        nil
type SecretOverridePtrInput interface {
	pulumi.Input

	ToSecretOverridePtrOutput() SecretOverridePtrOutput
	ToSecretOverridePtrOutputWithContext(context.Context) SecretOverridePtrOutput
}

type secretOverridePtrType SecretOverrideArgs

func SecretOverridePtr(v *SecretOverrideArgs) SecretOverridePtrInput {
	return (*secretOverridePtrType)(v)
}

func (*secretOverridePtrType) ElementType() reflect.Type {
	return reflect.TypeOf((**SecretOverride)(nil)).Elem()
}

func (i *secretOverridePtrType) ToSecretOverridePtrOutput() SecretOverridePtrOutput {
	return i.ToSecretOverridePtrOutputWithContext(context.Background())
}

func (i *secretOverridePtrType) ToSecretOverridePtrOutputWithContext(ctx context.Context) SecretOverridePtrOutput {
	return pulumi.ToOutputWithContext(ctx, i).(SecretOverridePtrOutput)
}

type SecretOverrideOutput struct{ *pulumi.OutputState }

func (SecretOverrideOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*SecretOverride)(nil)).Elem()
}

func (o SecretOverrideOutput) ToSecretOverrideOutput() SecretOverrideOutput {
	return o
}

func (o SecretOverrideOutput) ToSecretOverrideOutputWithContext(ctx context.Context) SecretOverrideOutput {
	return o
}

func (o SecretOverrideOutput) ToSecretOverridePtrOutput() SecretOverridePtrOutput {
	return o.ToSecretOverridePtrOutputWithContext(context.Background())
}

func (o SecretOverrideOutput) ToSecretOverridePtrOutputWithContext(ctx context.Context) SecretOverridePtrOutput {
	return o.ApplyTWithContext(ctx, func(_ context.Context, v SecretOverride) *SecretOverride {
		return &v
	}).(SecretOverridePtrOutput)
}

func (o SecretOverrideOutput) IsActive() pulumi.BoolOutput {
	return o.ApplyT(func(v SecretOverride) bool { return v.IsActive }).(pulumi.BoolOutput)
}

func (o SecretOverrideOutput) Value() pulumi.StringOutput {
	return o.ApplyT(func(v SecretOverride) string { return v.Value }).(pulumi.StringOutput)
}

type SecretOverridePtrOutput struct{ *pulumi.OutputState }

func (SecretOverridePtrOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**SecretOverride)(nil)).Elem()
}

func (o SecretOverridePtrOutput) ToSecretOverridePtrOutput() SecretOverridePtrOutput {
	return o
}

func (o SecretOverridePtrOutput) ToSecretOverridePtrOutputWithContext(ctx context.Context) SecretOverridePtrOutput {
	return o
}

func (o SecretOverridePtrOutput) Elem() SecretOverrideOutput {
	return o.ApplyT(func(v *SecretOverride) SecretOverride {
		if v != nil {
			return *v
		}
		var ret SecretOverride
		return ret
	}).(SecretOverrideOutput)
}

func (o SecretOverridePtrOutput) IsActive() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v *SecretOverride) *bool {
		if v == nil {
			return nil
		}
		return &v.IsActive
	}).(pulumi.BoolPtrOutput)
}

func (o SecretOverridePtrOutput) Value() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *SecretOverride) *string {
		if v == nil {
			return nil
		}
		return &v.Value
	}).(pulumi.StringPtrOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*SecretOverrideInput)(nil)).Elem(), SecretOverrideArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*SecretOverridePtrInput)(nil)).Elem(), SecretOverrideArgs{})
	pulumi.RegisterOutputType(SecretOverrideOutput{})
	pulumi.RegisterOutputType(SecretOverridePtrOutput{})
}
