// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

declare var exports: any;
const __config = new pulumi.Config("phase");

/**
 * The host URL for the Phase API. Can be set with PHASE_HOST environment variable.
 */
export declare const host: string | undefined;
Object.defineProperty(exports, "host", {
    get() {
        return __config.get("host");
    },
    enumerable: true,
});

/**
 * The token for authenticating with Phase. Can be a service token or a personal access token (PAT). Can be set with PHASE_TOKEN, PHASE_SERVICE_TOKEN, or PHASE_PAT_TOKEN environment variables.
 */
export declare const phaseToken: string | undefined;
Object.defineProperty(exports, "phaseToken", {
    get() {
        return __config.get("phaseToken") ?? utilities.getEnv("PHASE_TOKEN", "PHASE_SERVICE_TOKEN", "PHASE_PAT_TOKEN");
    },
    enumerable: true,
});

/**
 * Whether to skip SSL/TLS certificate validation for the PHASE_HOST. Defaults to false.
 */
export declare const skipTlsVerification: boolean | undefined;
Object.defineProperty(exports, "skipTlsVerification", {
    get() {
        return __config.getObject<boolean>("skipTlsVerification");
    },
    enumerable: true,
});

