// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package config

import (
	"github.com/jgautheron/pulumi-phase/sdk/go/phase/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi/config"
)

var _ = internal.GetEnvOrDefault

// The host URL for the Phase API. Can be set with PHASE_HOST environment variable.
func GetHost(ctx *pulumi.Context) string {
	return config.Get(ctx, "phase:host")
}

// The token for authenticating with Phase. Can be a service token or a personal access token (PAT). Can be set with PHASE_TOKEN, PHASE_SERVICE_TOKEN, or PHASE_PAT_TOKEN environment variables.
func GetPhaseToken(ctx *pulumi.Context) string {
	v, err := config.Try(ctx, "phase:phaseToken")
	if err == nil {
		return v
	}
	var value string
	if d := internal.GetEnvOrDefault(nil, nil, "PHASE_TOKEN", "PHASE_SERVICE_TOKEN", "PHASE_PAT_TOKEN"); d != nil {
		value = d.(string)
	}
	return value
}

// Whether to skip SSL/TLS certificate validation for the PHASE_HOST. Defaults to false.
func GetSkipTlsVerification(ctx *pulumi.Context) bool {
	return config.GetBool(ctx, "phase:skipTlsVerification")
}
