# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from .. import _utilities

host: Optional[str]
"""
The host URL for the Phase API. Can be set with PHASE_HOST environment variable.
"""

phaseToken: Optional[str]
"""
The token for authenticating with Phase. Can be a service token or a personal access token (PAT). Can be set with PHASE_TOKEN, PHASE_SERVICE_TOKEN, or PHASE_PAT_TOKEN environment variables.
"""

skipTlsVerification: Optional[bool]
"""
Whether to skip SSL/TLS certificate validation for the PHASE_HOST. Defaults to false.
"""

