# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
from . import _utilities
import typing
# Export this package's modules as members:
from .get_secrets import *
from .provider import *
from .secret import *
from ._inputs import *
from . import outputs

# Make subpackages available:
if typing.TYPE_CHECKING:
    import pulumi_phase.config as __config
    config = __config
else:
    config = _utilities.lazy_import('pulumi_phase.config')

_utilities.register(
    resource_modules="""
[
 {
  "pkg": "phase",
  "mod": "index/secret",
  "fqn": "pulumi_phase",
  "classes": {
   "phase:index/secret:Secret": "Secret"
  }
 }
]
""",
    resource_packages="""
[
 {
  "pkg": "phase",
  "token": "pulumi:providers:phase",
  "fqn": "pulumi_phase",
  "class": "Provider"
 }
]
"""
)
