# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities

__all__ = [
    'SecretOverrideArgs',
    'SecretOverrideArgsDict',
]

class SecretOverrideArgsDict(TypedDict):
    is_active: pulumi.Input[_builtins.bool]
    value: pulumi.Input[_builtins.str]

@pulumi.input_type
class SecretOverrideArgs:
    def __init__(__self__, *,
                 is_active: pulumi.Input[_builtins.bool],
                 value: pulumi.Input[_builtins.str]):
        pulumi.set(__self__, "is_active", is_active)
        pulumi.set(__self__, "value", value)

    @_builtins.property
    @pulumi.getter(name="isActive")
    def is_active(self) -> pulumi.Input[_builtins.bool]:
        return pulumi.get(self, "is_active")

    @is_active.setter
    def is_active(self, value: pulumi.Input[_builtins.bool]):
        pulumi.set(self, "is_active", value)

    @_builtins.property
    @pulumi.getter
    def value(self) -> pulumi.Input[_builtins.str]:
        return pulumi.get(self, "value")

    @value.setter
    def value(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "value", value)


