# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities

__all__ = [
    'GetSecretsResult',
    'AwaitableGetSecretsResult',
    'get_secrets',
    'get_secrets_output',
]

@pulumi.output_type
class GetSecretsResult:
    """
    A collection of values returned by getSecrets.
    """
    def __init__(__self__, app_id=None, env=None, id=None, key=None, path=None, secrets=None, tags=None):
        if app_id and not isinstance(app_id, str):
            raise TypeError("Expected argument 'app_id' to be a str")
        pulumi.set(__self__, "app_id", app_id)
        if env and not isinstance(env, str):
            raise TypeError("Expected argument 'env' to be a str")
        pulumi.set(__self__, "env", env)
        if id and not isinstance(id, str):
            raise TypeError("Expected argument 'id' to be a str")
        pulumi.set(__self__, "id", id)
        if key and not isinstance(key, str):
            raise TypeError("Expected argument 'key' to be a str")
        pulumi.set(__self__, "key", key)
        if path and not isinstance(path, str):
            raise TypeError("Expected argument 'path' to be a str")
        pulumi.set(__self__, "path", path)
        if secrets and not isinstance(secrets, dict):
            raise TypeError("Expected argument 'secrets' to be a dict")
        pulumi.set(__self__, "secrets", secrets)
        if tags and not isinstance(tags, list):
            raise TypeError("Expected argument 'tags' to be a list")
        pulumi.set(__self__, "tags", tags)

    @_builtins.property
    @pulumi.getter(name="appId")
    def app_id(self) -> _builtins.str:
        return pulumi.get(self, "app_id")

    @_builtins.property
    @pulumi.getter
    def env(self) -> _builtins.str:
        return pulumi.get(self, "env")

    @_builtins.property
    @pulumi.getter
    def id(self) -> _builtins.str:
        """
        The provider-assigned unique ID for this managed resource.
        """
        return pulumi.get(self, "id")

    @_builtins.property
    @pulumi.getter
    def key(self) -> Optional[_builtins.str]:
        return pulumi.get(self, "key")

    @_builtins.property
    @pulumi.getter
    def path(self) -> Optional[_builtins.str]:
        return pulumi.get(self, "path")

    @_builtins.property
    @pulumi.getter
    def secrets(self) -> Mapping[str, _builtins.str]:
        return pulumi.get(self, "secrets")

    @_builtins.property
    @pulumi.getter
    def tags(self) -> Optional[Sequence[_builtins.str]]:
        return pulumi.get(self, "tags")


class AwaitableGetSecretsResult(GetSecretsResult):
    # pylint: disable=using-constant-test
    def __await__(self):
        if False:
            yield self
        return GetSecretsResult(
            app_id=self.app_id,
            env=self.env,
            id=self.id,
            key=self.key,
            path=self.path,
            secrets=self.secrets,
            tags=self.tags)


def get_secrets(app_id: Optional[_builtins.str] = None,
                env: Optional[_builtins.str] = None,
                key: Optional[_builtins.str] = None,
                path: Optional[_builtins.str] = None,
                tags: Optional[Sequence[_builtins.str]] = None,
                opts: Optional[pulumi.InvokeOptions] = None) -> AwaitableGetSecretsResult:
    """
    Use this data source to access information about an existing resource.
    """
    __args__ = dict()
    __args__['appId'] = app_id
    __args__['env'] = env
    __args__['key'] = key
    __args__['path'] = path
    __args__['tags'] = tags
    opts = pulumi.InvokeOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke('phase:index/getSecrets:getSecrets', __args__, opts=opts, typ=GetSecretsResult).value

    return AwaitableGetSecretsResult(
        app_id=pulumi.get(__ret__, 'app_id'),
        env=pulumi.get(__ret__, 'env'),
        id=pulumi.get(__ret__, 'id'),
        key=pulumi.get(__ret__, 'key'),
        path=pulumi.get(__ret__, 'path'),
        secrets=pulumi.get(__ret__, 'secrets'),
        tags=pulumi.get(__ret__, 'tags'))
def get_secrets_output(app_id: Optional[pulumi.Input[_builtins.str]] = None,
                       env: Optional[pulumi.Input[_builtins.str]] = None,
                       key: Optional[pulumi.Input[Optional[_builtins.str]]] = None,
                       path: Optional[pulumi.Input[Optional[_builtins.str]]] = None,
                       tags: Optional[pulumi.Input[Optional[Sequence[_builtins.str]]]] = None,
                       opts: Optional[Union[pulumi.InvokeOptions, pulumi.InvokeOutputOptions]] = None) -> pulumi.Output[GetSecretsResult]:
    """
    Use this data source to access information about an existing resource.
    """
    __args__ = dict()
    __args__['appId'] = app_id
    __args__['env'] = env
    __args__['key'] = key
    __args__['path'] = path
    __args__['tags'] = tags
    opts = pulumi.InvokeOutputOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke_output('phase:index/getSecrets:getSecrets', __args__, opts=opts, typ=GetSecretsResult)
    return __ret__.apply(lambda __response__: GetSecretsResult(
        app_id=pulumi.get(__response__, 'app_id'),
        env=pulumi.get(__response__, 'env'),
        id=pulumi.get(__response__, 'id'),
        key=pulumi.get(__response__, 'key'),
        path=pulumi.get(__response__, 'path'),
        secrets=pulumi.get(__response__, 'secrets'),
        tags=pulumi.get(__response__, 'tags')))
