# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities

__all__ = ['ProviderArgs', 'Provider']

@pulumi.input_type
class ProviderArgs:
    def __init__(__self__, *,
                 host: Optional[pulumi.Input[_builtins.str]] = None,
                 phase_token: Optional[pulumi.Input[_builtins.str]] = None,
                 skip_tls_verification: Optional[pulumi.Input[_builtins.bool]] = None):
        """
        The set of arguments for constructing a Provider resource.

        :param pulumi.Input[_builtins.str] host: The host URL for the Phase API. Can be set with PHASE_HOST environment variable.
        :param pulumi.Input[_builtins.str] phase_token: The token for authenticating with Phase. Can be a service token or a personal access token (PAT). Can be set with PHASE_TOKEN, PHASE_SERVICE_TOKEN, or PHASE_PAT_TOKEN environment variables.
        :param pulumi.Input[_builtins.bool] skip_tls_verification: Whether to skip SSL/TLS certificate validation for the PHASE_HOST. Defaults to false.
        """
        if host is not None:
            pulumi.set(__self__, "host", host)
        if phase_token is None:
            phase_token = _utilities.get_env('PHASE_TOKEN', 'PHASE_SERVICE_TOKEN', 'PHASE_PAT_TOKEN')
        if phase_token is not None:
            pulumi.set(__self__, "phase_token", phase_token)
        if skip_tls_verification is not None:
            pulumi.set(__self__, "skip_tls_verification", skip_tls_verification)

    @_builtins.property
    @pulumi.getter
    def host(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        The host URL for the Phase API. Can be set with PHASE_HOST environment variable.
        """
        return pulumi.get(self, "host")

    @host.setter
    def host(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "host", value)

    @_builtins.property
    @pulumi.getter(name="phaseToken")
    def phase_token(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        The token for authenticating with Phase. Can be a service token or a personal access token (PAT). Can be set with PHASE_TOKEN, PHASE_SERVICE_TOKEN, or PHASE_PAT_TOKEN environment variables.
        """
        return pulumi.get(self, "phase_token")

    @phase_token.setter
    def phase_token(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "phase_token", value)

    @_builtins.property
    @pulumi.getter(name="skipTlsVerification")
    def skip_tls_verification(self) -> Optional[pulumi.Input[_builtins.bool]]:
        """
        Whether to skip SSL/TLS certificate validation for the PHASE_HOST. Defaults to false.
        """
        return pulumi.get(self, "skip_tls_verification")

    @skip_tls_verification.setter
    def skip_tls_verification(self, value: Optional[pulumi.Input[_builtins.bool]]):
        pulumi.set(self, "skip_tls_verification", value)


@pulumi.type_token("pulumi:providers:phase")
class Provider(pulumi.ProviderResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 host: Optional[pulumi.Input[_builtins.str]] = None,
                 phase_token: Optional[pulumi.Input[_builtins.str]] = None,
                 skip_tls_verification: Optional[pulumi.Input[_builtins.bool]] = None,
                 __props__=None):
        """
        The provider type for the phase package. By default, resources use package-wide configuration
        settings, however an explicit `Provider` instance may be created and passed during resource
        construction to achieve fine-grained programmatic control over provider settings. See the
        [documentation](https://www.pulumi.com/docs/reference/programming-model/#providers) for more information.


        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[_builtins.str] host: The host URL for the Phase API. Can be set with PHASE_HOST environment variable.
        :param pulumi.Input[_builtins.str] phase_token: The token for authenticating with Phase. Can be a service token or a personal access token (PAT). Can be set with PHASE_TOKEN, PHASE_SERVICE_TOKEN, or PHASE_PAT_TOKEN environment variables.
        :param pulumi.Input[_builtins.bool] skip_tls_verification: Whether to skip SSL/TLS certificate validation for the PHASE_HOST. Defaults to false.
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: Optional[ProviderArgs] = None,
                 opts: Optional[pulumi.ResourceOptions] = None):
        """
        The provider type for the phase package. By default, resources use package-wide configuration
        settings, however an explicit `Provider` instance may be created and passed during resource
        construction to achieve fine-grained programmatic control over provider settings. See the
        [documentation](https://www.pulumi.com/docs/reference/programming-model/#providers) for more information.


        :param str resource_name: The name of the resource.
        :param ProviderArgs args: The arguments to use to populate this resource's properties.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(ProviderArgs, pulumi.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 host: Optional[pulumi.Input[_builtins.str]] = None,
                 phase_token: Optional[pulumi.Input[_builtins.str]] = None,
                 skip_tls_verification: Optional[pulumi.Input[_builtins.bool]] = None,
                 __props__=None):
        opts = pulumi.ResourceOptions.merge(_utilities.get_resource_opts_defaults(), opts)
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.id is None:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = ProviderArgs.__new__(ProviderArgs)

            __props__.__dict__["host"] = host
            if phase_token is None:
                phase_token = _utilities.get_env('PHASE_TOKEN', 'PHASE_SERVICE_TOKEN', 'PHASE_PAT_TOKEN')
            __props__.__dict__["phase_token"] = None if phase_token is None else pulumi.Output.secret(phase_token)
            __props__.__dict__["skip_tls_verification"] = pulumi.Output.from_input(skip_tls_verification).apply(pulumi.runtime.to_json) if skip_tls_verification is not None else None
        secret_opts = pulumi.ResourceOptions(additional_secret_outputs=["phaseToken"])
        opts = pulumi.ResourceOptions.merge(opts, secret_opts)
        super(Provider, __self__).__init__(
            'phase',
            resource_name,
            __props__,
            opts)

    @_builtins.property
    @pulumi.getter
    def host(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        The host URL for the Phase API. Can be set with PHASE_HOST environment variable.
        """
        return pulumi.get(self, "host")

    @_builtins.property
    @pulumi.getter(name="phaseToken")
    def phase_token(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        The token for authenticating with Phase. Can be a service token or a personal access token (PAT). Can be set with PHASE_TOKEN, PHASE_SERVICE_TOKEN, or PHASE_PAT_TOKEN environment variables.
        """
        return pulumi.get(self, "phase_token")

    @pulumi.output_type
    class TerraformConfigResult:
        def __init__(__self__, result=None):
            if result and not isinstance(result, dict):
                raise TypeError("Expected argument 'result' to be a dict")
            pulumi.set(__self__, "result", result)

        @_builtins.property
        @pulumi.getter
        def result(self) -> Mapping[str, Any]:
            return pulumi.get(self, "result")

    def terraform_config(__self__) -> pulumi.Output['Provider.TerraformConfigResult']:
        """
        This function returns a Terraform config object with terraform-namecased keys,to be used with the Terraform Module Provider.
        """
        __args__ = dict()
        __args__['__self__'] = __self__
        return pulumi.runtime.call('pulumi:providers:phase/terraformConfig', __args__, res=__self__, typ=Provider.TerraformConfigResult)

