// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export function getSecrets(args: GetSecretsArgs, opts?: pulumi.InvokeOptions): Promise<GetSecretsResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("phase:index/getSecrets:getSecrets", {
        "appId": args.appId,
        "env": args.env,
        "key": args.key,
        "path": args.path,
        "tags": args.tags,
    }, opts);
}

/**
 * A collection of arguments for invoking getSecrets.
 */
export interface GetSecretsArgs {
    appId: string;
    env: string;
    key?: string;
    path?: string;
    tags?: string[];
}

/**
 * A collection of values returned by getSecrets.
 */
export interface GetSecretsResult {
    readonly appId: string;
    readonly env: string;
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly key?: string;
    readonly path?: string;
    readonly secrets: {[key: string]: string};
    readonly tags?: string[];
}
export function getSecretsOutput(args: GetSecretsOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetSecretsResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("phase:index/getSecrets:getSecrets", {
        "appId": args.appId,
        "env": args.env,
        "key": args.key,
        "path": args.path,
        "tags": args.tags,
    }, opts);
}

/**
 * A collection of arguments for invoking getSecrets.
 */
export interface GetSecretsOutputArgs {
    appId: pulumi.Input<string>;
    env: pulumi.Input<string>;
    key?: pulumi.Input<string>;
    path?: pulumi.Input<string>;
    tags?: pulumi.Input<pulumi.Input<string>[]>;
}
