// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export class Secret extends pulumi.CustomResource {
    /**
     * Get an existing Secret resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: SecretState, opts?: pulumi.CustomResourceOptions): Secret {
        return new Secret(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'phase:index/secret:Secret';

    /**
     * Returns true if the given object is an instance of Secret.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Secret {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === Secret.__pulumiType;
    }

    declare public readonly appId: pulumi.Output<string>;
    declare public readonly comment: pulumi.Output<string | undefined>;
    declare public /*out*/ readonly createdAt: pulumi.Output<string>;
    declare public readonly env: pulumi.Output<string>;
    declare public readonly key: pulumi.Output<string>;
    declare public readonly override: pulumi.Output<outputs.SecretOverride | undefined>;
    declare public readonly path: pulumi.Output<string | undefined>;
    declare public readonly tags: pulumi.Output<string[] | undefined>;
    declare public /*out*/ readonly updatedAt: pulumi.Output<string>;
    declare public readonly value: pulumi.Output<string>;
    declare public /*out*/ readonly version: pulumi.Output<number>;

    /**
     * Create a Secret resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: SecretArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: SecretArgs | SecretState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as SecretState | undefined;
            resourceInputs["appId"] = state?.appId;
            resourceInputs["comment"] = state?.comment;
            resourceInputs["createdAt"] = state?.createdAt;
            resourceInputs["env"] = state?.env;
            resourceInputs["key"] = state?.key;
            resourceInputs["override"] = state?.override;
            resourceInputs["path"] = state?.path;
            resourceInputs["tags"] = state?.tags;
            resourceInputs["updatedAt"] = state?.updatedAt;
            resourceInputs["value"] = state?.value;
            resourceInputs["version"] = state?.version;
        } else {
            const args = argsOrState as SecretArgs | undefined;
            if (args?.appId === undefined && !opts.urn) {
                throw new Error("Missing required property 'appId'");
            }
            if (args?.env === undefined && !opts.urn) {
                throw new Error("Missing required property 'env'");
            }
            if (args?.key === undefined && !opts.urn) {
                throw new Error("Missing required property 'key'");
            }
            if (args?.value === undefined && !opts.urn) {
                throw new Error("Missing required property 'value'");
            }
            resourceInputs["appId"] = args?.appId;
            resourceInputs["comment"] = args?.comment;
            resourceInputs["env"] = args?.env;
            resourceInputs["key"] = args?.key;
            resourceInputs["override"] = args?.override;
            resourceInputs["path"] = args?.path;
            resourceInputs["tags"] = args?.tags;
            resourceInputs["value"] = args?.value ? pulumi.secret(args.value) : undefined;
            resourceInputs["createdAt"] = undefined /*out*/;
            resourceInputs["updatedAt"] = undefined /*out*/;
            resourceInputs["version"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        const secretOpts = { additionalSecretOutputs: ["value"] };
        opts = pulumi.mergeOptions(opts, secretOpts);
        super(Secret.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering Secret resources.
 */
export interface SecretState {
    appId?: pulumi.Input<string>;
    comment?: pulumi.Input<string>;
    createdAt?: pulumi.Input<string>;
    env?: pulumi.Input<string>;
    key?: pulumi.Input<string>;
    override?: pulumi.Input<inputs.SecretOverride>;
    path?: pulumi.Input<string>;
    tags?: pulumi.Input<pulumi.Input<string>[]>;
    updatedAt?: pulumi.Input<string>;
    value?: pulumi.Input<string>;
    version?: pulumi.Input<number>;
}

/**
 * The set of arguments for constructing a Secret resource.
 */
export interface SecretArgs {
    appId: pulumi.Input<string>;
    comment?: pulumi.Input<string>;
    env: pulumi.Input<string>;
    key: pulumi.Input<string>;
    override?: pulumi.Input<inputs.SecretOverride>;
    path?: pulumi.Input<string>;
    tags?: pulumi.Input<pulumi.Input<string>[]>;
    value: pulumi.Input<string>;
}
